/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CouplesRouteImport } from './routes/couples'
import { Route as FamiliesRouteImport } from './routes/families'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PortraitsRouteImport } from './routes/portraits'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouplesRoute = CouplesRouteImport.update({
  id: '/couples',
  path: '/couples',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesRoute = FamiliesRouteImport.update({
  id: '/families',
  path: '/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PortraitsRoute = PortraitsRouteImport.update({
  id: '/portraits',
  path: '/portraits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/families': typeof FamiliesRoute
  '/portfolio': typeof PortfolioRoute
  '/portraits': typeof PortraitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/families': typeof FamiliesRoute
  '/portfolio': typeof PortfolioRoute
  '/portraits': typeof PortraitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/couples': typeof CouplesRoute
  '/families': typeof FamiliesRoute
  '/portfolio': typeof PortfolioRoute
  '/portraits': typeof PortraitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/couples' | '/families' | '/portfolio' | '/portraits'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/couples' | '/families' | '/portfolio' | '/portraits'
  id: '__root__' | '/' | '/couples' | '/families' | '/portfolio' | '/portraits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouplesRoute: typeof CouplesRoute
  FamiliesRoute: typeof FamiliesRoute
  PortfolioRoute: typeof PortfolioRoute
  PortraitsRoute: typeof PortraitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/couples': {
      id: '/couples'
      path: '/couples'
      fullPath: '/couples'
      preLoaderRoute: typeof CouplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families': {
      id: '/families'
      path: '/families'
      fullPath: '/families'
      preLoaderRoute: typeof FamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portraits': {
      id: '/portraits'
      path: '/portraits'
      fullPath: '/portraits'
      preLoaderRoute: typeof PortraitsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouplesRoute: CouplesRoute,
  FamiliesRoute: FamiliesRoute,
  PortfolioRoute: PortfolioRoute,
  PortraitsRoute: PortraitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
